### ISSUE TITLE
Fix tests for `get_authors` script

### ISSUE THREAD

**Issue by pvalena** [developer-portal/tools#4]
While addressing issues mentioned in PR #2:

- [x] Do not use `--global`
- [ ] Use helper function for `git ...` commands.
- [x] Add `mailto:` format.

**Comment by pvalena** [comment]
Currently, the script is not portable. See CI run in #6.

**Comment by jackorp** [comment]
Could this issue get closed as PR [#10](https://github.com/developer-portal/tools/pull/10) got merged and Travis CI tests passed?

**Comment by pvalena** [comment]
> Could this issue get closed as PR #10 got merged and Travis CI tests passed?



Let's finish the last checkbox too (see updated [first comment](https://github.com/developer-portal/tools/issues/4#issue-308158643) of this issue).

**Comment by pvalena** [comment]
Any news on this?

**Comment by jackorp** [comment]
See [PR#13](https://github.com/developer-portal/tools/pull/13)
